#!/usr/bin/env python3
"""
Build the English version of AGMX (app-en.js / data-en.js) from the
Bahasa Melayu sources (app.js / data.js) via ordered string replacement.

Usage:  python3 tools/build_en.py
Run from the repository root. Pairs are applied longest-source-first so
phrases win over single words. Status strings used in JS comparisons
(e.g. "Selesai", "Sedang Berlangsung", "LULUS") are translated in BOTH
files, keeping the logic consistent.
"""
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent

PAIRS = [
    # ---------- Long phrases: quotes, sentences, paragraphs ----------
    ("Bukan sekadar aplikasi telesidang. AGMX ialah Sistem Operasi Tadbir Urus Koperasi menyeluruh — Microsoft 365 + Zoom + SPR + DocuSign + Sistem Audit, digabungkan dalam satu platform SaaS.",
     "Not just a teleconferencing app. AGMX is a complete Cooperative Governance Operating System — Microsoft 365 + Zoom + an election commission + DocuSign + an audit system, combined into one SaaS platform."),
    ("Koperasi bercadang membahagikan 8% daripada keuntungan kepada semua ahli sebagai dividen. Sebagai contoh, jika anda mempunyai 1,500 unit saham, anda akan menerima RM 120.",
     "The cooperative proposes to distribute 8% of profits to all members as dividends. For example, if you own 1,500 share units, you will receive RM 120."),
    ("Pendapatan koperasi meningkat 9.8% kepada RM 12.84 juta, dengan untung bersih RM 1.42 juta. Dividen 8% dicadangkan — melebihi purata 3 tahun sebelumnya.",
     "Cooperative revenue grew 9.8% to RM 12.84 million, with net profit of RM 1.42 million. An 8% dividend is proposed — above the previous 3-year average."),
    ("Semua data, notis, dan pematuhan telah disahkan. Hanya satu klik untuk menerbitkan AGM dan mula menerima kehadiran.",
     "All data, notices, and compliance have been verified. Just one click to publish the AGM and start accepting attendance."),
    ("Aktifkan paparan mesra warga emas dengan butang besar (60-80px), teks lebih besar, kontras tinggi, dan navigasi ringkas (One Screen, One Action).",
     "Enable a senior-friendly display with large buttons (60-80px), bigger text, high contrast, and simple navigation (One Screen, One Action)."),
    ("Saya menyokong penuh kadar dividen 8% — ia adalah munasabah dan selari dengan prestasi tahun ini.",
     "I fully support the 8% dividend rate — it is reasonable and aligned with this year's performance."),
    ("Ahli sekalian, kita sekarang membincangkan pembahagian dividen 8% daripada lebih surplus RM 1.42 juta...",
     "Members, we are now discussing the 8% dividend distribution from the RM 1.42 million surplus..."),
    ("Walaupun kadar lebih rendah, jumlah dividen diagih lebih tinggi (+3.6%) kerana lebih surplus meningkat 29%.",
     "Although the rate is lower, the total dividend distributed is higher (+3.6%) because the net surplus grew 29%."),
    ("Kempen kesedaran menumpukan Zero Training Required — warga emas boleh mengundi dalam 5 minit.",
     "Awareness campaign focused on Zero Training Required — seniors can vote within 5 minutes."),
    ("Sasaran 100 koperasi terbesar di Malaysia yang menghadapi isu kuorum & pertikaian E-Voting.",
     "Targeting Malaysia's 100 largest cooperatives facing quorum issues & e-voting disputes."),
    ("Kerjasama dengan Suruhanjaya Koperasi Malaysia untuk menjadikan AGMX standard kepatuhan.",
     "Partnership with the Malaysia Co-operative Societies Commission to make AGMX the compliance standard."),
    ("M-001 telahpun mendapat 248 undi YA. Kuorum terjawab. Boleh tutup fasa undian dalam 2 minit.",
     "M-001 has already received 248 YES votes. Quorum satisfied. The voting phase can close in 2 minutes."),
    ("M-003 tidak memenuhi Klausa 7.3 UUK (tiada Penyokong dalam 15 minit). Auto-gugur dicadangkan.",
     "M-003 does not meet UUK Clause 7.3 (no Seconder within 15 minutes). Auto-drop recommended."),
    ("12 soalan berulang tentang Dividen — satukan menjadi 1 untuk dijawab Bendahari sekaligus.",
     "12 repeated questions about Dividends — merge into 1 for the Treasurer to answer at once."),
    ("Draf minit AGM Ke-16 sedang dijana. Dijangka siap dalam 4 minit (98% ketepatan).",
     "The 16th AGM minutes draft is being generated. Expected ready in 4 minutes (98% accuracy)."),
    ("2 resolusi AGM Ke-15 masih belum selesai. Papar status kepatuhan di AG-04?",
     "2 resolutions from the 15th AGM are still incomplete. Show compliance status in AG-04?"),
    ("12 soalan ahli tentang \"Dividen\" boleh digabung menjadi 1 untuk dijawab sekaligus.",
     "12 member questions about \"Dividends\" can be merged into 1 to answer at once."),
    ("Semua notis dihantar 21 hari lebih awal — melebihi minimum UUK 15 hari.",
     "All notices sent 21 days in advance — exceeding the 15-day UUK minimum."),
    ("Setiap langkah disimpan automatik. Anda boleh kembali dan menyunting pada bila-bila masa.",
     "Every step is saved automatically. You can go back and edit at any time."),
    ("Persidangan diteruskan dengan Agenda AG-06 — Pembahagian Dividen & Lebih Surplus.",
     "The conference continues with Agenda AG-06 — Dividend & Surplus Distribution."),
    ("Maaf, berlaku ralat semasa memaparkan halaman ini. Sila cuba semula.",
     "Sorry, an error occurred while displaying this page. Please try again."),
    ("Sila pilih YA atau TIDAK. Anda boleh tukar pilihan sebelum menghantar.",
     "Please choose YES or NO. You can change your choice before submitting."),
    ("1 usul (M-001) melebihi had 15 minit perbahasan. Tindakan pengerusi diperlukan.",
     "1 motion (M-001) exceeded the 15-minute debate limit. Chairman action required."),
    ("Kuorum disahkan — 403 daripada 1,284 ahli hadir (31.4%) — melepasi syarat minimum UUK 25%.",
     "Quorum confirmed — 403 of 1,284 members present (31.4%) — exceeding the UUK 25% minimum."),
    ("Minit AGM Ke-15 disahkan tanpa pindaan oleh En. Vijay Kumar dan disokong Pn. Wong Soke Yen.",
     "15th AGM minutes confirmed without amendment by Mr. Vijay Kumar, seconded by Mrs. Wong Soke Yen."),
    ("Penyata Kewangan TK 2025 dibentang — Hasil RM 12.84J, Untung RM 1.42J, Dividen 8% dicadangkan.",
     "FY 2025 Financial Statements presented — Revenue RM 12.84M, Profit RM 1.42M, 8% dividend proposed."),
    ("Pelantikan Juruaudit Luar — LULUS (381 YA, 12 TIDAK, 8 KOSONG).",
     "External Auditor Appointment — PASSED (381 YES, 12 NO, 8 ABSTAIN)."),
    ("Pindaan UUK 7.3 — GAGAL (tiada Penyokong dalam 15 minit, BRule-003 dipicu).",
     "UUK 7.3 Amendment — FAILED (no Seconder within 15 minutes, BRule-003 triggered)."),
    ("Sedang berlangsung — M-001 pembahagian dividen sedang diundi.",
     "Ongoing — M-001 dividend distribution currently being voted."),
    ("Mesyuarat dipengerusikan oleh Dato' Ariffin Bin Kassim (Pengerusi).",
     "The meeting was chaired by Dato' Ariffin Bin Kassim (Chairman)."),
    ("Tarikh: 23 Jun 2026 · Masa: 09:04 – (berlangsung) · Tempat: Dewan Korporat KOPEMAJU",
     "Date: 23 Jun 2026 · Time: 09:04 – (ongoing) · Venue: KOPEMAJU Corporate Hall"),
    ("MINIT MESYUARAT AGUNG TAHUNAN KE-16", "MINUTES OF THE 16TH ANNUAL GENERAL MEETING"),
    ("Assalamualaikum dan Salam Sejahtera ahli KOPEMAPU sekalian,",
     "Greetings to all KOPEMAJU members,"),
    ("Dimaklumkan bahawa Mesyuarat Agung Tahunan Ke-17 akan diadakan...",
     "Please be informed that the 17th Annual General Meeting will be held..."),
    ("[ ... AI auto-lengkapkan dari data koperasi ... ]", "[ ... AI auto-completes from cooperative data ... ]"),
    ("Notis Mesyuarat Agung Tahunan Ke-17 KOPEMAJU", "Notice of the 17th KOPEMAJU Annual General Meeting"),
    ("Dewan Korporat KOPEMAJU & Dalam Talian", "KOPEMAJU Corporate Hall & Online"),
    ("Sebarang kesulitan? Telefon terus:", "Any difficulty? Call directly:"),
    ("Pentadbir akan menelefon anda dalam 30 saat", "An admin will call you within 30 seconds"),
    ("Sistem auto-kesan percubaan daftar masuk berganda", "System auto-detects duplicate check-in attempts"),
    ("1 proksi ditolak (tidak berdaftar dengan SKM)", "1 proxy rejected (not registered with SKM)"),
    ("2 ahli disekat hari ini (BRule-005)", "2 members blocked today (BRule-005)"),
    ("313 daripada 403 ahli berkuorum telah mengundi · Tamat: 11:45",
     "313 of 403 quorum members have voted · Ends: 11:45"),
    ("ahli berkuorum telah mengundi (", "quorum members have voted ("),
    ("ahli berkuorum telah mengundi · Akan tutup pada 11:45",
     "quorum members have voted · Closes at 11:45"),
    ("Boleh penjelasan tentang formula pengiraan?", "Could you explain the calculation formula?"),
    ("Boleh penjelasan formula pengiraan?", "Could you explain the calculation formula?"),
    ("Saya menyokong penuh — kadar dividen 8% adalah munasabah.",
     "I fully support this — the 8% dividend rate is reasonable."),
    ("Mengapa kadar dividen lebih rendah berbanding TK 2024 (10%)?",
     "Why is the dividend rate lower than FY 2024 (10%)?"),
    ("Adakah koperasi akan membuka cawangan di Klang?", "Will the cooperative open a branch in Klang?"),
    ("Bagaimana mekanisme bantuan kewangan kecemasan untuk ahli?",
     "How does the emergency financial aid mechanism for members work?"),
    ("Boleh jelaskan pelaburan hartanah baru di Cyberjaya?",
     "Could you explain the new property investment in Cyberjaya?"),
    ("Selesai pelantikan juruaudit luar & tandatangan surat setuju",
     "Complete external auditor appointment & sign engagement letter"),
    ("Agihkan dividen 8% kepada akaun ahli melalui eWallet",
     "Distribute 8% dividend to member accounts via eWallet"),
    ("Sediakan kertas kerja pindaan UUK 7.3 untuk AGM Ke-17",
     "Prepare UUK 7.3 amendment working paper for the 17th AGM"),
    ("Mesyuarat dimulakan, kuorum disahkan", "Meeting started, quorum confirmed"),
    ("Audio diterjemah masa nyata oleh AI", "Audio translated in real time by AI"),
    ("Pembahagian Dividen 8% daripada Lebih Surplus RM1.42 Juta",
     "8% Dividend Distribution from RM1.42 Million Net Surplus"),
    ("Pembahagian Dividen 8% daripada Lebih Surplus RM 1.42 Juta",
     "8% Dividend Distribution from RM 1.42 Million Net Surplus"),
    ("Pelantikan Juruaudit Luar Bertauliah Bagi TK 2026",
     "Appointment of Certified External Auditor for FY 2026"),
    ("Pindaan UUK Klausa 7.3: Kuorum Mesyuarat Agung",
     "UUK Clause 7.3 Amendment: General Meeting Quorum"),
    ("daripada Lebih Surplus RM 1.42 Juta", "from RM 1.42 Million Net Surplus"),
    ("daripada Lebih Surplus", "from Net Surplus"),
    ("Memperkasa digitalisasi koperasi & kesejahteraan ahli.",
     "Empowering cooperative digitalization & member well-being."),
    ("Inovasi produk & perluasan pasaran generasi muda.",
     "Product innovation & expanding the youth market."),
    ("Mempertahankan warisan & integriti kewangan.", "Preserving heritage & financial integrity."),
    ("Memperkenalkan platform e-dagang untuk ahli.", "Introducing an e-commerce platform for members."),
    ("Memperkukuh jaringan koperasi wanita & komuniti.",
     "Strengthening women's cooperative & community networks."),
    ("Latihan keusahawanan & modal insan.", "Entrepreneurship training & human capital."),
    ("Pekhidmatan kesihatan & kebajikan veteran.", "Healthcare services & veteran welfare."),
    ("Transformasi teknologi & keselamatan siber.", "Technology transformation & cybersecurity."),
    # ---------- Data: agenda, compliance, misc ----------
    ("Pengerusian & Ucapan Alu-aluan", "Chairmanship & Welcome Address"),
    ("Pengesahan Kuorum & Notis Mesyuarat", "Quorum & Meeting Notice Confirmation"),
    ("Pengesahan Minit AGM Ke-15", "Confirmation of 15th AGM Minutes"),
    ("Pembentangan Penyata Kewangan 2025", "Presentation of 2025 Financial Statements"),
    ("Laporan Tahunan & Pencapaian", "Annual Report & Achievements"),
    ("Pembahagian Dividen & Lebih Surplus", "Dividend & Surplus Distribution"),
    ("Pilihan Raya Lembaga Pengarah 2026-2029", "Board of Directors Election 2026-2029"),
    ("Pilihan Raya Lembaga 2026-2029", "Board Election 2026-2029"),
    ("Pilihan Raya Lembaga · 45 minit", "Board Election · 45 minutes"),
    ("Usul-Usul Ahli", "Members' Motions"),
    ("Hal-Hal Lain & Penutup", "Other Matters & Closing"),
    ("Notis Mesyuarat (≥15 hari)", "Meeting Notice (≥15 days)"),
    ("21 hari — dihantar 02 Jun 2026", "21 days — sent 02 Jun 2026"),
    ("Kelayakan Mengundi Ahli Aktif", "Active Member Voting Eligibility"),
    ("Tapis automatik (1,162 layak / 122 tidak layak)", "Auto-filtered (1,162 eligible / 122 ineligible)"),
    ("Kuorum Minimum (≥25%)", "Minimum Quorum (≥25%)"),
    ("31.4% — 403 daripada 1,284 ahli", "31.4% — 403 of 1,284 members"),
    ("Pencadang & Penyokong Usul", "Motion Proposer & Seconder"),
    ("Setiap usul dijejaki secara automatik", "Every motion tracked automatically"),
    ("1 usul melebihi 15 minit pada M-001", "1 motion exceeded 15 minutes on M-001"),
    ("Rekod Digital Tidak Boleh Dipadam", "Digital Records Cannot Be Deleted"),
    ("Immutable hash chain aktif", "Immutable hash chain active"),
    ("Mesyuarat Agung Tahunan Ke-16", "16th Annual General Meeting"),
    ("Mesyuarat Agung Tahunan Ke-17", "17th Annual General Meeting"),
    ("AGM Ke-16 (Tahun Kewangan 2025)", "16th AGM (Financial Year 2025)"),
    ("Dewan Korporat KOPEMAJU, Petaling Jaya", "KOPEMAJU Corporate Hall, Petaling Jaya"),
    ("Hibrid (Fizikal + Dalam Talian)", "Hybrid (Physical + Online)"),
    ("Setiausaha (Secretary)", "Secretary"),
    ("Undi YA pada M-001", "YES vote on M-001"),
    ("Undi TIDAK pada M-001", "NO vote on M-001"),
    ("Sokong M-001", "Seconded M-001"),
    ("Cadang M-001 (Dividen 8%)", "Proposed M-001 (8% Dividend)"),
    ("Buka fasa Voting Mode", "Opened Voting Mode phase"),
    ("Bahagian Kewangan", "Finance Department"),
    # ---------- Statuses used in comparisons (must match both files) ----------
    ("Selesai — LULUS", "Completed — PASSED"),
    ("Gagal — Tiada Penyokong", "Failed — No Seconder"),
    ("Sedang Diundi", "Voting Open"),
    ("SEDANG DIUNDI", "VOTING IN PROGRESS"),
    ("Sedang Berlangsung", "In Progress"),
    ("SEDANG BERLANGSUNG", "IN PROGRESS"),
    ("Belum Bermula", "Not Started"),
    ("Dalam Tindakan", "In Action"),
    ("Dalam Antrian", "In Queue"),
    ("Disatukan", "Merged"),
    ("Dijawab", "Answered"),
    # ---------- Section titles / nav ----------
    ("Pengurusan keahlian & kelayakan undi", "Membership management & voting eligibility"),
    ("Persidangan Hibrid · Mod Voting", "Hybrid Conference · Voting Mode"),
    ("Galeri calon pilihan raya lembaga", "Board election candidate gallery"),
    ("Enjin rantaian usul & minit mesyuarat", "Motion chain engine & meeting minutes"),
    ("Multi-ejen RAG · Ejen pintar", "Multi-agent RAG · Smart agents"),
    ("Lejar kalis ubah · Hash chain", "Tamper-proof ledger · Hash chain"),
    ("Aksesibiliti, bahasa & senior mode", "Accessibility, language & senior mode"),
    ("Cipta mesyuarat agung · 5 langkah dipandu", "Create your AGM · 5 guided steps"),
    ("Antaramuka One Click Join untuk ahli", "One Click Join interface for members"),
    ("Pelan 3-fasa → Cooperative SuperApp", "3-phase plan → Cooperative SuperApp"),
    ("Ringkasan AGM & Kuorum", "AGM Overview & Quorum"),
    ("Pendaftaran Kehadiran", "Attendance Registration"),
    ("Papan Pemuka Pentadbir", "Admin Dashboard"),
    ("Papan Pemuka", "Dashboard"),
    ("Ahli & Organisasi", "Members & Organization"),
    ("Dewan AGM — Layout", "AGM Hall — Layout"),
    ("Masuk Dewan AGM", "Enter AGM Hall"),
    ("Dewan AGM", "AGM Hall"),
    ("E-Voting Pintar", "Smart E-Voting"),
    ("Usul & Resolusi", "Motions & Resolutions"),
    ("Pematuhan SKM & Akta Koperasi", "SKM & Cooperative Act Compliance"),
    ("Pematuhan SKM", "SKM Compliance"),
    ("Mod Warga Emas", "Senior Citizen Mode"),
    ("Mod Mesra Warga Emas", "Senior Friendly Mode"),
    ("Pendaftaran QR", "QR Check-in"),
    ("Calon & Undian", "Candidates & Ballots"),
    ("Umum & Aksesibiliti", "General & Accessibility"),
    ("AGM Wizard · Cipta Mesyuarat Agung", "AGM Wizard · Create General Meeting"),
    # ---------- Enterprise shell: statusbar, confirm dialogs, rail ----------
    ("Kuncup atau kembangkan menu sisi", "Collapse or expand the sidebar"),
    ("Kuncup/Kembang menu", "Collapse/expand menu"),
    ("Status sistem", "System status"),
    ("Sistem Dalam Talian", "System Online"),
    ("Hash chain disegerak", "Hash chain synced"),
    ("Mengesahkan OTP...", "Verifying OTP..."),
    ("Pilih semua", "Select all"),
    ('aria-label="Tutup"', 'aria-label="Close"'),
    ("Akhiri Mesyuarat?", "End the Meeting?"),
    ("Semua sesi ahli akan ditamatkan dan minit akhir akan dimuktamadkan. Tindakan ini tidak boleh dibatalkan.",
     "All member sessions will be terminated and the final minutes will be locked. This action cannot be undone."),
    ("Ya, Akhiri Mesyuarat", "Yes, End Meeting"),
    ("Mesyuarat ditamatkan. Minit akhir sedang dijana.", "Meeting ended. Final minutes are being generated."),
    ("Akhiri mesyuarat", "End the meeting"),
    ("Akhiri Mesyuarat", "End Meeting"),
    ("Tutup Undian M-001?", "Close Voting on M-001?"),
    ("313 daripada 403 ahli telah mengundi. Ahli yang belum mengundi tidak akan dapat mengundi selepas ini.",
     "313 of 403 members have voted. Members who have not voted will no longer be able to vote."),
    ("✅ Undian M-001 ditutup. Keputusan dimuktamadkan.", "✅ Voting on M-001 closed. Results finalized."),
    ("Hantar Undi Anda?", "Submit Your Ballot?"),
    ("Anda memilih ${n} calon. Selepas dihantar, undi anda dimeterai secara kriptografi dan <b>tidak boleh diubah</b>.",
     "You selected ${n} candidates. Once submitted, your ballot is cryptographically sealed and <b>cannot be changed</b>."),
    ("Ya, Hantar Undi", "Yes, Submit Ballot"),
    ("✅ Undi anda telah dihantar & direkodkan dalam hash chain.",
     "✅ Your ballot has been submitted & recorded in the hash chain."),
    ('"Sahkan"', '"Confirm"'),
    # ---------- Header / theme / language ----------
    ("AGMX Aplikasi Tadbir Urus Koperasi", "AGMX Cooperative Governance Application"),
    ("Tukar ke mod cerah", "Switch to light mode"),
    ("Tukar ke mod gelap", "Switch to dark mode"),
    ("🌙 Mod Gelap diaktifkan", "🌙 Dark Mode enabled"),
    ("☀️ Mod Cerah diaktifkan", "☀️ Light Mode enabled"),
    ("Mod Cerah", "Light Mode"),
    ("Mod Gelap", "Dark Mode"),
    ("Buka menu navigasi", "Open navigation menu"),
    ("Tutup menu", "Close menu"),
    ("Pemberitahuan", "Notifications"),
    ("🧓 Senior Friendly Mode: AKTIF", "🧓 Senior Friendly Mode: ON"),
    ("Senior Mode dimatikan", "Senior Mode turned off"),
    # ---------- Copilot drawer ----------
    ("4 ejen aktif · RAG + Audit Sentiasa", "4 active agents · RAG + Always-on Audit"),
    ("Tutup Undian", "Close Voting"),
    ("Lanjutkan 2 min", "Extend 2 min"),
    ("Auto-Gugur", "Auto-Drop"),
    ("Maklum Pengerusi", "Notify Chairman"),
    ("Cadangan Pintar", "Smart Suggestions"),
    ("Buka Copilot Penuh", "Open Full Copilot"),
    # ---------- Login ----------
    ("Sistem Operasi Tadbir Urus Koperasi", "Cooperative Governance Operating System"),
    ("Log masuk untuk mengurus", "Log in to manage"),
    ("Pilih Peranan Anda", "Choose Your Role"),
    ("Pentadbir AGM", "AGM Administrator"),
    ("Kawalan dewan", "Hall controls"),
    ("Masukkan 6-digit OTP yang dihantar", "Enter the 6-digit OTP sent to you"),
    ("Sah & Masuk AGM", "Verify & Enter AGM"),
    ("Kod tamat dalam 02:48", "Code expires in 02:48"),
    ("Hantar semula", "Resend"),
    ("Bukan ahli?", "Not a member?"),
    ("Passkey: Gunakan cap jari / Face ID", "Passkey: Use fingerprint / Face ID"),
    ("🔐 Log masuk berjaya. Selamat datang ke AGM Ke-16!", "🔐 Login successful. Welcome to the 16th AGM!"),
    # ---------- Dashboard ----------
    ("Selamat Datang, Pn. Aishah 👋", "Welcome, Mrs. Aishah 👋"),
    ("AGM Ke-16 sedang berjalan · Hari ke-2 persidangan · Kuorum 31.4%",
     "16th AGM in progress · Conference day 2 · Quorum 31.4%"),
    ("Eksport Laporan", "Export Report"),
    ("Pratonton Senior", "Senior Preview"),
    ("Notis (3)", "Notices (3)"),
    ("Cipta AGM", "Create AGM"),
    ("Imbas QR ahli · Real-time check-in · Auto-sync dengan Dewan AGM",
     "Scan member QR · Real-time check-in · Auto-sync with AGM Hall"),
    ("Imbas QR", "Scan QR"),
    ("Jumlah Ahli", "Total Members"),
    ("+8.2% tahun ke tahun", "+8.2% year on year"),
    ("Undian Setakat Ini", "Votes So Far"),
    ("↑ Aktif dalam", "↑ Active in"),
    ("Sesi AGM Aktif", "AGM Session Active"),
    ("Sesi AGM", "AGM Session"),
    ("Tamat dalam 1j 42m", "Ends in 1h 42m"),
    ("Skor Pematuhan", "Compliance Score"),
    ("Semua Sistem Normal", "All Systems Normal"),
    ("Sesi Aktif", "Active Sessions"),
    ("ahli sedang online", "members online now"),
    ("↓ 8 ms dari semalam", "↓ 8 ms vs yesterday"),
    ("Auto-scaling aktif", "Auto-scaling active"),
    ("2 aktif", "2 active"),
    ("Compliance + Chairman", "Compliance + Chairman"),
    ("Senarai Agenda Aktif", "Active Agenda List"),
    ("Ringkasan Kewangan TK 2025 (AI Ringkasan)", "FY 2025 Financial Summary (AI Summary)"),
    ("Auto-jana: Trend Untung Bersih 5 Tahun", "Auto-generated: 5-Year Net Profit Trend"),
    ("Auto-jana", "Auto-generated"),
    ("Untung Bersih (RM Juta)", "Net Profit (RM Million)"),
    ("Trend Untung Bersih (5 tahun)", "Net Profit Trend (5 years)"),
    ("↑ +73% dalam 5 tahun", "↑ +73% over 5 years"),
    ("Untung Bersih", "Net Profit"),
    ("Dividen Dicadangkan", "Proposed Dividend"),
    ("Status Kuorum", "Quorum Status"),
    ("Syarat minimum:", "Minimum requirement:"),
    ("Mod: Hibrid · Fizikal: 142 · Dalam Talian: 261", "Mode: Hybrid · Physical: 142 · Online: 261"),
    ("Satukan Soalan", "Merge Questions"),
    ("Pek Mesyuarat Digital", "Digital Meeting Pack"),
    ("PDF · 4 halaman · Dihantar 02 Jun", "PDF · 4 pages · Sent 02 Jun"),
    ("PDF · 12 halaman", "PDF · 12 pages"),
    ("PDF · 28 halaman", "PDF · 28 pages"),
    ("PDF · 64 halaman", "PDF · 64 pages"),
    ("AI-generated · Sedang dijana", "AI-generated · Generating"),
    ("Draf Minit AGM-16", "AGM-16 Minutes Draft"),
    ("Penyata Kewangan 2025", "2025 Financial Statements"),
    ("Laporan Tahunan", "Annual Report"),
    ("Notis AGM Dihantar", "AGM Notices Sent"),
    ("Notis AGM < 15 hari", "AGM notice < 15 days"),
    ("Notis AGM", "AGM Notice"),
    ("Menjana", "Generating"),
    # ---------- Members ----------
    ("ahli berdaftar", "registered members"),
    ("layak mengundi", "eligible to vote"),
    ("Eksport CSV", "Export CSV"),
    ("Tambah Ahli", "Add Member"),
    ("Layak Mengundi", "Eligible to Vote"),
    ("Auto-tapis aktif", "Auto-filter active"),
    ("Perlu penjelasan SKM", "SKM clarification needed"),
    ("Menggunakan Proksi", "Using Proxy"),
    ("Surat proksi disahkan", "Proxy letters verified"),
    ("Cari nama atau no. ahli...", "Search name or member no..."),
    ("✓ Layak Undi", "✓ Eligible"),
    ("✗ Tidak Layak", "✗ Ineligible"),
    ("Nama & No. Ahli", "Name & Member No."),
    ("Kelayakan Undi", "Voting Eligibility"),
    ("Kehadiran", "Attendance"),
    ("Disekat", "Blocked"),
    ("Hadir di dewan", "Attend in hall"),
    (">Hadir<", ">Present<"),
    (">Belum<", ">Not Yet<"),
    ("Tiada ahli padanan dengan carian", "No members match your search"),
    (">Sebelum<", ">Prev<"),
    (">Seterus<", ">Next<"),
    # ---------- Hall ----------
    ("Buka Mod Voting", "Open Voting Mode"),
    ("Pengerusi KOPEMAJU", "KOPEMAJU Chairman"),
    ("Sedang bercakap", "Speaking now"),
    ("🎤 Sedang bercakap", "🎤 Speaking now"),
    ("M-001 sedang diundi", "M-001 being voted"),
    ("🔊 Transkrip Langsung · Auto-translate", "🔊 Live Transcript · Auto-translate"),
    ("Memperbahasan M-001", "Debating M-001"),
    ("Pencadang M-001", "Proposer of M-001"),
    ("Analisis Untung Bersih TK 2025", "FY 2025 Net Profit Analysis"),
    ("Slaid 14 / 28", "Slide 14 / 28"),
    ("Senarai Penceramah (Speaker Queue)", "Speaker Queue"),
    ("Live Caption & Translate", "Live Caption & Translate"),
    ("Calon Pengerusi", "Chairman Candidate"),
    ("Agenda Sesi", "Session Agenda"),
    ("Soalan Digabung", "Questions Merged"),
    ("12 soalan tentang Dividen → 1 soalan", "12 questions about Dividends → 1 question"),
    ("Peringatan", "Reminder"),
    ("M-001 berbaki 4 minit sebelum auto-tutup", "M-001 has 4 minutes left before auto-close"),
    ("M-003 auto-gugur (tiada Penyokong)", "M-003 auto-dropped (no Seconder)"),
    ("4 menunggu", "4 waiting"),
    ("Proksi aktif", "Proxy active"),
    ("Baru daftar", "Just registered"),
    ("Butang Panik", "Panic Button"),
    ("Saya Perlukan Bantuan", "I Need Help"),
    ("Mikrofon", "Microphone"),
    ("Kamera Diaktifkan", "Camera Enabled"),
    ("Kamera", "Camera"),
    ("Skrin", "Screen"),
    ("Tangan", "Raise Hand"),
    ("Akhiri", "End Meeting"),
    ("Rekod", "Record"),
    # ---------- Voting ----------
    ("calon · Pilih sehingga 1 Pengerusi, 1 Naib, dan 6 Ahli Lembaga",
     "candidates · Choose up to 1 Chairman, 1 Deputy, and 6 Board Members"),
    ("Bagaimana Mengundi?", "How to Vote?"),
    ("Fasa Pengundian Aktif", "Voting Phase Active"),
    ("Hantar Undi", "Submit Vote"),
    ("Naib Pengerusi", "Deputy Chairman"),
    ("Ahli Lembaga", "Board Member"),
    ("Zon PJ Utara", "PJ North Zone"),
    ("Cari calon...", "Search candidates..."),
    ("undi diterima", "votes received"),
    ("% sokongan", "% support"),
    ("Pilih Calon", "Select Candidate"),
    (">Dipilih<", ">Selected<"),
    ("calon dipilih", "candidates selected"),
    ("Kosongkan", "Clear"),
    ("Sah & Hantar", "Confirm & Submit"),
    ("Naib (", "Deputy ("),
    # ---------- Motions ----------
    ("Enjin Rantaian Usul", "Motion Chain Engine"),
    ("usul direkodkan · BRule-001 hingga BRule-005 dipantau",
     "motions recorded · BRule-001 to BRule-005 monitored"),
    ("Eksport Minit", "Export Minutes"),
    ("Cadang Usul", "Propose Motion"),
    ("Jumlah Usul", "Total Motions"),
    ("Tahun ini", "This year"),
    ("Diluluskan", "Approved"),
    ("Auto-dokumentasi", "Auto-documented"),
    ("Live sekarang", "Live now"),
    ("📝 Pencadang:", "📝 Proposer:"),
    ("✓ Penyokong:", "✓ Seconder:"),
    ("⏱️ Dicadang:", "⏱️ Proposed:"),
    (">Tiada<", ">None<"),
    ("Tiada</span>", "None</span>"),
    ("AI Minute Writer — Draf Minit Mesyuarat", "AI Minute Writer — Meeting Minutes Draft"),
    ("Sedang dijana · 68% siap", "Generating · 68% done"),
    ("Sah & Tandatangan Digital", "Confirm & Digitally Sign"),
    ("Eksport PDF", "Export PDF"),
    ("Perbaiki dengan AI", "Refine with AI"),
    ("Tadbir Urus", "Governance"),
    ("Kewangan", "Financial"),
    # ---------- Copilot page ----------
    ("Peringatan prosedur proaktif", "Proactive procedure reminders"),
    ("Speech-to-text & auto-minit", "Speech-to-text & auto-minutes"),
    ("Satukan soalan berulang", "Merge repeated questions"),
    ("Multi-ejen pintar · RAG diindeks dengan", "Smart multi-agent · RAG indexed with"),
    ("rekod ·", "records ·"),
    ("Upload Dokumen", "Upload Documents"),
    ("Ejen Baru", "New Agent"),
    ("Ejen Aktif", "Active Agents"),
    ("Status Sistem", "System Status"),
    ("RAG Indeks: 1,247 dokumen", "RAG Index: 1,247 documents"),
    ("Aktif sekarang", "Active now"),
    ("Selamat sejahtera Pn. Aishah 👋 Saya", "Greetings Mrs. Aishah 👋 I am"),
    (". Saya boleh membantu dengan analisis kewangan, semakan pematuhan, dan ringkasan minit mesyuarat. Ada apa yang ingin saya bantu?",
     ". I can help with financial analysis, compliance checks, and meeting minutes summaries. How can I assist you?"),
    ("Berapa dividen tahun lepas berbanding tahun ini?", "How does last year's dividend compare to this year's?"),
    ("Perbandingan Dividen KOPEMAJU (TK 2024 vs TK 2025):", "KOPEMAJU Dividend Comparison (FY 2024 vs FY 2025):"),
    ("(RM 1.10J daripada lebih surplus RM 1.10J)", "(RM 1.10M from RM 1.10M net surplus)"),
    ("(RM 1.14J daripada lebih surplus RM 1.42J)", "(RM 1.14M from RM 1.42M net surplus)"),
    ("8% (dicadangkan)", "8% (proposed)"),
    ("📄 Sumber:", "📄 Source:"),
    ("Penyata Kewangan 2025 (M/S 14, Para 3.2)", "2025 Financial Statements (p. 14, Para 3.2)"),
    ("Adakah ini melanggar UUK?", "Does this violate the UUK?"),
    ("Tidak melanggar.", "No violation."),
    ("Semakan AI Compliance:", "AI Compliance check:"),
    ("UUK Klausa 8.1: Dividen minimum 5% —", "UUK Clause 8.1: Minimum dividend 5% —"),
    ("Akta Koperasi 1993 Sec 22(3): Lebih surplus diagih —",
     "Cooperative Act 1993 Sec 22(3): Net surplus distributed —"),
    ("GP14B: Sekurang-kurangnya 20% lebih surplus dikekalkan —",
     "GP14B: At least 20% of net surplus retained —"),
    ("(RM 280K dikekalkan)", "(RM 280K retained)"),
    ("⚖️ Rujukan:", "⚖️ Reference:"),
    ("Garis Panduan 14B", "Guideline 14B"),
    ("Klausa 8.1 UUK KOPEMAJU", "KOPEMAJU UUK Clause 8.1"),
    ("Dibaca ✓✓", "Read ✓✓"),
    ("📊 Ringkaskan Penyata Kewangan", "📊 Summarize Financial Statements"),
    ("⚖️ Semak pematuhan UUK", "⚖️ Check UUK compliance"),
    ("📝 Jana draf minit", "📝 Generate minutes draft"),
    ("🔍 Cari resolusi AGM Ke-15", "🔍 Find 15th AGM resolutions"),
    ("Tanya soalan tentang AGM, kewangan atau pematuhan...", "Ask about the AGM, finances or compliance..."),
    ("Soalan Dijawab", "Questions Answered"),
    ("+27 hari ini", "+27 today"),
    ("Dokumen Diindeks", "Documents Indexed"),
    ("RAG siap carian", "RAG search-ready"),
    ("Draf Minit", "Minutes Drafts"),
    ("AI jana automatik", "AI auto-generated"),
    ("Alert Pematuhan", "Compliance Alerts"),
    ("Auto-block tindakan", "Auto-block actions"),
    ("AI Action Tracker — Tugas Pasca-AGM", "AI Action Tracker — Post-AGM Tasks"),
    ("3 tugasan aktif", "3 active tasks"),
    ("Keutamaan Tinggi", "High Priority"),
    # ---------- Compliance ----------
    ("Enjin Compliance-by-Design", "Compliance-by-Design Engine"),
    ("Laporan Pematuhan", "Compliance Report"),
    ("Jana Audit SKM", "Generate SKM Audit"),
    ("1 Amaran Aktif — UUK 7.3: Tempoh Perbahasan", "1 Active Warning — UUK 7.3: Debate Duration"),
    ("Lihat Butiran", "View Details"),
    ("Skor Digital Governance · PATUH TINGGI", "Digital Governance Score · HIGHLY COMPLIANT"),
    ("↑ +3 mata dari audit lepas (95)", "↑ +3 points since last audit (95)"),
    ("5 Patuh", "5 Compliant"),
    ("1 Amaran", "1 Warning"),
    ("✓ Patuh (", "✓ Compliant ("),
    ("⚠ Amaran (", "⚠ Warning ("),
    ("Statistik Pematuhan", "Compliance Statistics"),
    ("21 hari lebih awal", "21 days early"),
    ("Auto-tapis", "Auto-filtered"),
    ("Kuorum Dipantau", "Quorum Monitored"),
    ("Pencadang & Penyokong", "Proposer & Seconder"),
    ("Tempoh Perbahasan", "Debate Duration"),
    ("1 usul > 15 minit", "1 motion > 15 minutes"),
    ("100% immutabel", "100% immutable"),
    ("Matriks Peraturan Perniagaan", "Business Rules Matrix"),
    ("Kuorum minimum tidak tercapai", "Minimum quorum not reached"),
    ("Butang Start Meeting dinyahaktifkan", "Start Meeting button disabled"),
    ("Usul tiada Pencadang", "Motion without Proposer"),
    ("Sesi Open Discussion disekat", "Open Discussion session blocked"),
    ("Tiada Penyokong dalam 15 min", "No Seconder within 15 min"),
    ("Auto-gugur + rekod minit", "Auto-drop + record in minutes"),
    ("Sekat terbitan notis", "Block notice publication"),
    ("Ahli Tunggakan mengundi", "Member in arrears voting"),
    ("Akses undian disekat", "Voting access blocked"),
    ("peraturan", "rules"),
    # ---------- Vault ----------
    ("Lejar Kalis Ubah · Immutable Hash Chain · 7,891 blok direkodkan sejak 2010",
     "Tamper-Proof Ledger · Immutable Hash Chain · 7,891 blocks recorded since 2010"),
    ("Eksport untuk SKM", "Export for SKM"),
    ("Verifikasi Integriti Sekarang", "Verify Integrity Now"),
    ("Verifikasi Integriti", "Verify Integrity"),
    ("Blok Disimpan", "Blocks Stored"),
    ("Rantaian tidak boleh diubah", "Immutable chain"),
    ("Integriti Chain", "Chain Integrity"),
    ("Disahkan secara berkriptografi", "Cryptographically verified"),
    ("Penyulitan", "Encryption"),
    ("Backup Lokasi", "Backup Locations"),
    ("Geo-redundan aktif", "Geo-redundancy active"),
    ("Cari ID ahli, hash, atau tindakan...", "Search member ID, hash, or action..."),
    (">Undi<", ">Votes<"),
    (">Usul<", ">Motions<"),
    (">Sistem<", ">System<"),
    ("Cap Masa", "Timestamp"),
    ("Aktor", "Actor"),
    (">Tindakan<", ">Action<"),
    (">Tanda<", ">Sig<"),
    ("rekod terkini · 7,891 dalam arkib", "latest records · 7,891 in archive"),
    ("Muat Lagi ↓", "Load More ↓"),
    ("Buka Arkib Penuh →", "Open Full Archive →"),
    ("🔗 Rantaian Hash", "🔗 Hash Chain"),
    ("7,891 blok", "7,891 blocks"),
    ("🔍 Tuding untuk hash", "🔍 Hover for hash"),
    ("+ 7,888 blok terdahulu · semua disahkan ✓", "+ 7,888 earlier blocks · all verified ✓"),
    ("✅ Verifikasi terakhir: 11:42:18 (SHA-256)", "✅ Last verified: 11:42:18 (SHA-256)"),
    ("⏳ Menyemak 7,891 blok...", "⏳ Checking 7,891 blocks..."),
    ("✅ Integriti 100% Disahkan", "✅ Integrity 100% Verified"),
    ("✅ Verifikasi selesai: 7,891/7,891 blok sah (SHA-256)",
     "✅ Verification complete: 7,891/7,891 blocks valid (SHA-256)"),
    ("Aktif untuk semua peranan", "Active for all roles"),
    ("Data in-transit & at-rest", "Data in-transit & at-rest"),
    ("Cloudflare WAF aktif", "Cloudflare WAF active"),
    ("Malaysia + ASEAN sahaja", "Malaysia + ASEAN only"),
    ("Session fingerprint enforced", "Session fingerprint enforced"),
    ("Live monitoring aktif", "Live monitoring active"),
    # ---------- Settings ----------
    ("Tetapan & Aksesibiliti", "Settings & Accessibility"),
    ("Senior Friendly Mode · Bahasa · Tema · Premium", "Senior Friendly Mode · Language · Theme · Premium"),
    ("Saiz butang: 60-80px", "Button size: 60-80px"),
    ("Teks: +20%", "Text: +20%"),
    ("Menu: ≤5 item", "Menu: ≤5 items"),
    ("🎨 Tema Paparan", "🎨 Display Theme"),
    ("Kontras Tinggi", "High Contrast"),
    (">Lalai<", ">Default<"),
    (">Gelap<", ">Dark<"),
    ("'Lalai'", "'Default'"),
    ("'Gelap'", "'Dark'"),
    ("Aksesibiliti", "Accessibility"),
    (">Malam<", ">Night<"),
    ("'Malam'", "'Night'"),
    ("🌐 Bahasa & Locale", "🌐 Language & Locale"),
    ("Bahasa Antaramuka", "Interface Language"),
    ("💎 Langganan SaaS", "💎 SaaS Subscription"),
    ("Pelan Aktif", "Active Plan"),
    ("RM 2,500 / tahun · sehingga 1,000 ahli", "RM 2,500 / year · up to 1,000 members"),
    ("Ahli digunakan", "Members used"),
    ("Pembaharuan", "Renewal"),
    ("Tidak aktif", "Inactive"),
    ("⬆️ Naik Taraf ke Platinum", "⬆️ Upgrade to Platinum"),
    ("📱 Peranti Aktif", "📱 Active Devices"),
    ("2 jam lalu", "2 hours ago"),
    ("Log Keluar", "Log Out"),
    ("🔌 Integrasi & API", "🔌 Integrations & API"),
    ("Belum disambungkan", "Not connected"),
    # ---------- Dropdowns / notifications / profile / search ----------
    ("M-001: 12 undi baru diterima", "M-001: 12 new votes received"),
    ("248 YA · 47 TIDAK · 18 KOSONG", "248 YES · 47 NO · 18 ABSTAIN"),
    ("AI Minute Writer siap 68%", "AI Minute Writer 68% done"),
    ("Draf minit AGM-16 sedang dijana · dijangka siap 4 minit",
     "AGM-16 minutes draft generating · ready in ~4 minutes"),
    ("M-003 auto-gugur", "M-003 auto-dropped"),
    ("BRule-003 dipicu: Tiada Penyokong dalam 15 minit", "BRule-003 triggered: No Seconder within 15 minutes"),
    ("Pematuhan 100% LULUS", "Compliance 100% PASSED"),
    ("Semua 6 syarat SKM dipatuhi untuk AGM-16", "All 6 SKM requirements met for AGM-16"),
    ("Pn. Fatimah Ismail daftar masuk", "Mrs. Fatimah Ismail checked in"),
    ("Kaedah: MyKad NFC · No. Ahli A-0312", "Method: MyKad NFC · Member No. A-0312"),
    ("WebSocket latency turun 8ms", "WebSocket latency down 8ms"),
    ("Optimisasi auto-scaling selesai", "Auto-scaling optimization complete"),
    ("AG-07 akan dimulakan", "AG-07 starting soon"),
    ("Baru saja", "Just now"),
    ("minit lalu", "minutes ago"),
    ("3 belum dibaca", "3 unread"),
    ("Tanda Semua Dibaca", "Mark All Read"),
    ("Lihat Semua Pemberitahuan", "View All Notifications"),
    ("Tukar Peranan (Demo)", "Switch Role (Demo)"),
    ("Tetapan Akaun", "Account Settings"),
    ("Keutamaan Pemberitahuan", "Notification Preferences"),
    ("Bantuan & Sokongan", "Help & Support"),
    ("Pintasan Papan Kekunci", "Keyboard Shortcuts"),
    ("Peranan ditukar:", "Role switched:"),
    ("👋 Anda telah log keluar", "👋 You have logged out"),
    ("Ciri ini akan datang dalam versi penuh.", "This feature is coming in the full version."),
    ("Ciri ini akan datang. Sila hubungi pentadbir jika perlu.",
     "Coming soon. Please contact the administrator if needed."),
    ("Cari ahli, usul, agenda, atau apa-apa...", "Search members, motions, agenda, or anything..."),
    ("Taip untuk mula mencari...", "Type to start searching..."),
    ("Mencari dalam", "Searching across"),
    ("Cuba:", "Try:"),
    ("Tiada hasil untuk", "No results for"),
    ("A-0078 (Muthusamy)", "A-0078 (Muthusamy)"),
    ("Pergi ke", "Going to"),
    ('type: "Ahli"', 'type: "Member"'),
    ('type: "Usul"', 'type: "Motion"'),
    ('type: "Calon"', 'type: "Candidate"'),
    (" saham · ", " shares · "),
    # ---------- Wizard ----------
    ("Asas AGM", "AGM Basics"),
    ("Tarikh & mod", "Date & mode"),
    ("Susun atur agenda", "Arrange agenda"),
    ("Notis & Hebahan", "Notice & Distribution"),
    ("Saluran pengedaran", "Distribution channels"),
    ("Auto-checks SKM", "SKM auto-checks"),
    ("Terbit AGM Sekarang", "Publish AGM Now"),
    ("Terbit AGM", "Publish AGM"),
    ("Sedia dimulakan", "Ready to start"),
    ("5 langkah · Auto-pematuhan Akta Koperasi 1993 · Auto-jana Notis & Minit",
     "5 steps · Auto-compliance with Cooperative Act 1993 · Auto-generate Notice & Minutes"),
    ("Batal", "Cancel"),
    ("Panduan", "Guide"),
    ("💡 Tip Auto-Save", "💡 Auto-Save Tip"),
    ("Langkah 1: Asas AGM", "Step 1: AGM Basics"),
    ("Tetapkan tarikh, masa, dan mod persidangan", "Set the date, time, and conference mode"),
    ("Tajuk AGM", "AGM Title"),
    ("Edisi / Tahun Kewangan", "Edition / Financial Year"),
    ("Masa Mula", "Start Time"),
    ("Tempoh (jam)", "Duration (hours)"),
    ("Mod Persidangan", "Conference Mode"),
    ("Fizikal + Dalam Talian", "Physical + Online"),
    ("Paling Popular", "Most Popular"),
    ("PALING POPULAR", "MOST POPULAR"),
    ("Fizikal Sahaja", "Physical Only"),
    ("Lokasi (jika fizikal/hibrid)", "Location (if physical/hybrid)"),
    ("Kuorum Minimum (%)", "Minimum Quorum (%)"),
    ("Langkah 2: Agenda Builder", "Step 2: Agenda Builder"),
    ("Tambah dan susun atur item agenda", "Add and arrange agenda items"),
    ("7 item · 165 minit", "7 items · 165 minutes"),
    ("Tambah Item Agenda", "Add Agenda Item"),
    ("⏱️ Anggaran Masa", "⏱️ Estimated Time"),
    ("Slaid AI tersedia: 28 muka surat · Minit: 12 hal.", "AI slides ready: 28 pages · Minutes: 12 pp."),
    ("Langkah 3: Notis & Hebahan", "Step 3: Notice & Distribution"),
    ("Pilih saluran pengedaran notis AGM", "Choose AGM notice distribution channels"),
    ("ahli akan menerima", "members will receive"),
    ("Saluran Pengedaran", "Distribution Channels"),
    ("E-mel", "Email"),
    ("Notifikasi App", "App Notifications"),
    ("Surat Fizikal", "Physical Mail"),
    ("Tarikh Hantar Notis", "Notice Send Date"),
    ("✓ Hantar 21 hari sebelum AGM — melebihi minimum UUK 15 hari",
     "✓ Sent 21 days before the AGM — exceeds the 15-day UUK minimum"),
    ("Templat Notis (AI-jana)", "Notice Template (AI-generated)"),
    ("Langkah 4: Auto-Pematuhan SKM", "Step 4: SKM Auto-Compliance"),
    ("Sistem mengesahkan semua keperluan Akta Koperasi 1993",
     "The system verifies all Cooperative Act 1993 requirements"),
    ("Notis Mesyuarat dihantar ≥15 hari", "Meeting Notice sent ≥15 days"),
    ("Notis akan dihantar 21 hari sebelum AGM (margin 6 hari)",
     "Notice will be sent 21 days before the AGM (6-day margin)"),
    ("Kuorum minimum ditakrifkan", "Minimum quorum defined"),
    ("25% daripada 1,284 ahli = 321 ahli minimum", "25% of 1,284 members = 321 members minimum"),
    ("Semua resolusi melalui Pencadang + Penyokong", "All resolutions via Proposer + Seconder"),
    ("Enjin BRule-002/003 akan menguatkuasakan", "BRule-002/003 engine will enforce"),
    ("Sekurang-kurangnya 20% lebih surplus dikekalkan", "At least 20% of net surplus retained"),
    ("Auto-kira dalam minit AI", "Auto-calculated in AI minutes"),
    ("Tempoh perbahasan ≤15 minit setiap usul", "Debate duration ≤15 minutes per motion"),
    ("Auto-timer aktif dalam Dewan AGM", "Auto-timer active in the AGM Hall"),
    ("Rekod digital tidak boleh diubah", "Digital records cannot be altered"),
    ("Immutable hash chain akan diaktifkan untuk AGM ini",
     "Immutable hash chain will be enabled for this AGM"),
    ("Semua Pematuhan LULUS", "All Compliance Checks PASSED"),
    ("AGM ini bersedia untuk diterbitkan dan diedarkan kepada ahli",
     "This AGM is ready to be published and distributed to members"),
    ("Langkah 5: Sedia Terbit! 🚀", "Step 5: Ready to Publish! 🚀"),
    ("Semak ringkasan akhir dan terbitkan AGM", "Review the final summary and publish the AGM"),
    ("Semua Sedia", "All Set"),
    ("AGM Anda Telah Diconfigurasikan", "Your AGM Has Been Configured"),
    ("Tarikh AGM", "AGM Date"),
    ("Ahli Dinotis", "Members Notified"),
    ("Saluran Aktif", "Active Channels"),
    ("Simpan Draf", "Save Draft"),
    ("← Sebelum", "← Back"),
    ("Seterusnya →", "Next →"),
    ("Langkah ${step} daripada 5", "Step ${step} of 5"),
    ("🎉 AGM Ke-17 diterbitkan! Notis dihantar kepada 1,284 ahli.",
     "🎉 17th AGM published! Notices sent to 1,284 members."),
    # ---------- Senior ----------
    ("📞 Hubungi Saya", "📞 Call Me"),
    ("Selamat Datang, Pn. Fatimah", "Welcome, Mrs. Fatimah"),
    ("Ahli KOPEMAJU sejak 2010 · No. Ahli A-0312", "KOPEMAJU member since 2010 · Member No. A-0312"),
    ("Senarai Agenda", "Agenda List"),
    ("7 perkara · AG-06 aktif", "7 items · AG-06 active"),
    ("Dokumen AGM", "AGM Documents"),
    ("4 fail tersedia", "4 files available"),
    ("Undi Sekarang", "Vote Now"),
    ("1 undian menunggu anda", "1 ballot awaiting you"),
    ("Tanya Soalan", "Ask a Question"),
    ("AI akan susun soalan", "AI will organize questions"),
    ("📞 Hotline Pengerusi", "📞 Chairman Hotline"),
    ("(8 pagi - 10 malam)", "(8 am - 10 pm)"),
    ("← Kembali", "← Back"),
    ("🗳️ Pengundian Anda", "🗳️ Your Ballot"),
    ("Dalam bahasa mudah:", "In simple terms:"),
    ("Saya setuju", "I agree"),
    ("Saya tidak setuju", "I disagree"),
    ("🛡️ Undi Anda Dilindungi", "🛡️ Your Vote Is Protected"),
    ("Disulitkan AES-256 · Direkodkan kekal dalam lejar KOPEMAJU",
     "AES-256 encrypted · Permanently recorded in the KOPEMAJU ledger"),
    ("Anda Telah Mengundi!", "You Have Voted!"),
    (") telah direkodkan dengan selamat. Terima kasih, Pn. Fatimah! 🎉",
     ") has been securely recorded. Thank you, Mrs. Fatimah! 🎉"),
    ("🧾 Resit digital: #7892 · 11:43 · Disulitkan AES-256",
     "🧾 Digital receipt: #7892 · 11:43 · AES-256 encrypted"),
    ("✅ Undi anda (", "✅ Your vote ("),
    (") berjaya dihantar. Terima kasih!", ") was submitted successfully. Thank you!"),
    ("📋 Apa Yang Akan Dibincangkan", "📋 What Will Be Discussed"),
    # ---------- Scanner ----------
    ("📷 Meja Pendaftaran Kehadiran", "📷 Attendance Check-in Desk"),
    ("Eksport Senarai", "Export List"),
    ("Cetak QR Mesra", "Print Friendly QR"),
    ("QR Scanner Aktif", "QR Scanner Active"),
    ("Arahkan kod QR ahli ke kamera", "Point the member's QR code at the camera"),
    ("Tukar Kamera", "Switch Camera"),
    ("Sesi Imbas Terkini", "Recent Scans"),
    ("24 dalam 5 minit", "24 in 5 minutes"),
    ("Syarat 25%", "Threshold 25%"),
    ("Mod Check-in", "Check-in Modes"),
    ("Imbas kod QR peribadi ahli", "Scan member's personal QR code"),
    ("Sentuh kad pengenalan", "Tap identity card"),
    ("Taip no. ahli secara manual", "Type member no. manually"),
    ("Beta — untuk ahli berdaftar", "Beta — for registered members"),
    ("⚠️ Sekatan Automatik", "⚠️ Automatic Blocks"),
    ("Tunggakan Saham/Yuran", "Share/Fee Arrears"),
    ("Proksi Tidak Sah", "Invalid Proxy"),
    ("Dual Check-in Dicegah", "Duplicate Check-in Prevented"),
    # ---------- Roadmap ----------
    ("Pelan 3-fasa daripada MVP hingga \"Cooperative SuperApp\" · Vol 1 + Vol 10 PRD",
     "3-phase plan from MVP to \"Cooperative SuperApp\" · Vol 1 + Vol 10 PRD"),
    ("Eksport Roadmap PDF", "Export Roadmap PDF"),
    ("Kongsi dengan Lembaga", "Share with Board"),
    ("🎯 Visi Jangka Panjang", "🎯 Long-Term Vision"),
    ("Sasaran 2028", "Target 2028"),
    ("✅ Fasa 1 · MVP", "✅ Phase 1 · MVP"),
    ("4 bulan · Selesai", "4 months · Completed"),
    ("Ciri-ciri asas AGM dengan pematuhan Compliance-by-Design",
     "Core AGM features with Compliance-by-Design"),
    ("100% siap", "100% done"),
    ("✓ Pengurusan Ahli (CSV)", "✓ Member Management (CSV)"),
    ("✓ AGM Wizard (5 langkah)", "✓ AGM Wizard (5 steps)"),
    ("✓ Imbasan QR Kehadiran", "✓ QR Attendance Scanning"),
    ("✓ E-Voting Asas (AES-256)", "✓ Basic E-Voting (AES-256)"),
    ("✓ Satu-Skrin-Satu-Tindakan UI", "✓ One-Screen-One-Action UI"),
    ("🔄 Fasa 2 · V1", "🔄 Phase 2 · V1"),
    ("3 bulan · Sedang berjalan", "3 months · Ongoing"),
    ("Persidangan hibrid + AI Governance + Enjin Pematuhan Penuh",
     "Hybrid conference + AI Governance + Full Compliance Engine"),
    ("78% siap", "78% done"),
    ("✓ Mod Hibrid (5 Layout)", "✓ Hybrid Mode (5 Layouts)"),
    ("✓ Enjin Pematuhan SKM", "✓ SKM Compliance Engine"),
    ("✓ Multi-Ejen AI Copilot", "✓ Multi-Agent AI Copilot"),
    ("✓ Notifikasi Bersepadu", "✓ Unified Notifications"),
    ("○ Action Tracker Penuh", "○ Full Action Tracker"),
    ("⏳ Fasa 3 · V2", "⏳ Phase 3 · V2"),
    ("4 bulan · Akan datang", "4 months · Upcoming"),
    ("Penskalaan mega + integrasi kerajaan + AI Legal Assistant",
     "Mega scaling + government integration + AI Legal Assistant"),
    ("18% siap", "18% done"),
    ("○ Multi-Tenant 100k+ ahli", "○ Multi-Tenant 100k+ members"),
    ("○ Pembantu Perundangan AI", "○ AI Legal Assistant"),
    ("🚀 Fasa 4 · 2028", "🚀 Phase 4 · 2028"),
    ("Visi · Cooperative SuperApp", "Vision · Cooperative SuperApp"),
    ("Bukan lagi AGM app — Sistem memori institusi koperasi",
     "No longer an AGM app — a cooperative institutional memory system"),
    ("Konseptual", "Conceptual"),
    ("◆ AI Memory Institusi", "◆ Institutional AI Memory"),
    ("Modul Selesai", "Modules Completed"),
    ("daripada 40+ dirancang", "of 40+ planned"),
    ("Auto-checks aktif", "Auto-checks active"),
    ("📅 Garis Masa Pelancaran", "📅 Launch Timeline"),
    ("🚀 Pelancaran MVP", "🚀 MVP Launch"),
    ("100 koperasi pertama · Subscription Starter RM500",
     "First 100 cooperatives · Starter subscription RM500"),
    ("🧠 Pelancaran AI Copilot", "🧠 AI Copilot Launch"),
    ("RAG + Multi-Agent · 1,247 dokumen diindeks", "RAG + Multi-Agent · 1,247 documents indexed"),
    ("🏛️ Fasa 2 Siap", "🏛️ Phase 2 Complete"),
    ("🌏 Peluasan ASEAN", "🌏 ASEAN Expansion"),
    ("Pejabat Sumatera · Multi-bahasa penuh", "Sumatra office · Full multi-language"),
    ("⚖️ Fasa 3 Enterprise", "⚖️ Phase 3 Enterprise"),
    ("Multi-tenant 100k+ ahli · Government Cloud", "Multi-tenant 100k+ members · Government Cloud"),
    ("Cooperative SuperApp · Sasaran ARR RM 50M", "Cooperative SuperApp · ARR target RM 50M"),
    ("📈 Strategi Go-To-Market (GTM)", "📈 Go-To-Market (GTM) Strategy"),
    ("Jualan Langsung (B2B)", "Direct Sales (B2B)"),
    ("Rakan Strategik SKM", "SKM Strategic Partner"),
    ("Pemasaran Digital", "Digital Marketing"),
    ("Status: Aktif", "Status: Active"),
    ("Status: Dalam rundingan", "Status: In negotiation"),
    ("💰 Pelan Langganan SaaS", "💰 SaaS Subscription Plans"),
    ("50 ahli", "50 members"),
    ("300 ahli", "300 members"),
    ("1,000 ahli", "1,000 members"),
    ("1,000+ ahli", "1,000+ members"),
    ("Semua Starter", "All Starter"),
    ("Semua Pro", "All Pro"),
    ("Semua Enterprise", "All Enterprise"),
    ("Semua Platinum", "All Platinum"),
    ("1 Bahasa", "1 Language"),
    ("Multi-bahasa", "Multi-language"),
    ("AI Copilot Penuh", "Full AI Copilot"),
    ("API Integrasi", "API Integration"),
    ("/ tahun", "/ year"),
    # ---------- Misc / generic (applied last by length) ----------
    ("Ralat Tidak Dijangka", "Unexpected Error"),
    ("Muat Semula", "Reload"),
    (">Tutup<", ">Close<"),
    ("Undi anda (<b>", "Your vote (<b>"),
    ("> Belum<", "> Not Yet<"),
    ("AI sedang menaip", "AI is typing"),
    ("Bantuan 24/7", "24/7 Help"),
    ("Berbanding audit lepas", "Compared to last audit"),
    ("Hubungi saya", "Call me"),
    ("Trend untung bersih 5 years: RM 820K (2021) ke RM 1,420K (2025)",
     "5-year net profit trend: RM 820K (2021) to RM 1,420K (2025)"),
    ("Layout Pengundian", "Voting Layout"),
    ("dinyahaktifkan", "disabled"),
    ("diaktifkan", "enabled"),
    ("Aktifkan", "Enable"),
    ("Pengundian", "Voting"),
    ("Persidangan", "Conference"),
    ("Pembentangan", "Presentation"),
    ("Perbahasan", "Debate"),
    ("Pengerusi", "Chairman"),
    ("Setiausaha", "Secretary"),
    ("Bendahari", "Treasurer"),
    ("Suruhanjaya", "Commission"),
    ("Pencadang", "Proposer"),
    ("Penyokong", "Seconder"),
    ("Tunggakan", "Arrears"),
    ("tunggakan", "arrears"),
    ("Menunggu", "Waiting"),
    ("Selesai", "Completed"),
    (" selesai", " completed"),
    ("Undian", "Voting"),
    ("Diundi", "Voting Open"),
    ("Mengundi", "Vote"),
    ("mengundi", "vote"),
    ("KOSONG", "ABSTAIN"),
    ("M-001 · YA", "M-001 · YES"),
    ("M-001 · TIDAK", "M-001 · NO"),
    (">YA<", ">YES<"),
    (">TIDAK<", ">NO<"),
    ('"YA"', '"YES"'),
    ('"TIDAK"', '"NO"'),
    (" YA (", " YES ("),
    ("undi YA", "YES votes"),
    (" undi", " votes"),
    ("Kuorum", "Quorum"),
    ("kuorum", "quorum"),
    ("Hibrid", "Hybrid"),
    ("hibrid", "hybrid"),
    ("Fizikal", "Physical"),
    ("fizikal", "physical"),
    ("Dalam Talian", "Online"),
    ("PATUH TINGGI", "HIGHLY COMPLIANT"),
    ("PATUH", "COMPLIANT"),
    ("AMARAN", "WARNING"),
    ("Amaran", "Warning"),
    ("LULUS", "PASSED"),
    ("GAGAL", "FAILED"),
    ("Gagal", "Failed"),
    ("AKTIF", "ACTIVE"),
    ("Aktif", "Active"),
    (" aktif", " active"),
    ("Semua", "All"),
    ("Proksi", "Proxy"),
    ("proksi", "proxy"),
    ("Saham", "Shares"),
    ("Layak", "Eligible"),
    ("Dividen", "Dividend"),
    ("Hasil", "Revenue"),
    ("Sasaran", "Target"),
    ("Eksport", "Export"),
    ("Tetapan", "Settings"),
    ("Pematuhan", "Compliance"),
    (" Juta", " Million"),
    ("Tahun Kewangan", "Financial Year"),
    ("tahun lepas", "last year"),
    ("tahun ini", "this year"),
    (" tahun", " years"),
    (" minit lalu", " minutes ago"),
    (" minit", " minutes"),
    (" daripada ", " of "),
    (" dokumen", " documents"),
    (" ahli hadir", " members present"),
    (" ahli · ", " members · "),
    (" ahli (", " members ("),
    (" ahli sedang", " members currently"),
    (" ahli", " members"),
    (" usul ", " motions "),
    (" usul<", " motions<"),
    (" halaman", " pages"),
    (" dihantar", " delivered"),
    ("Paparan ", "Showing "),
    ("Pn. ", "Mrs. "),
    ("En. ", "Mr. "),
    ("Cik ", "Ms. "),
    ("Ahli", "Member"),
    ("Tarikh", "Date"),
    ("Tapis:", "Filter:"),
    (" ejen", " agents"),
    ("Zon ", "Zone "),
    ("Lalai", "Default"),
]

# EN-only fixups applied AFTER the main pass (language switch link, AI-translate demo lines)
EN_FIXUPS = [
    ('href="app-en.html${location.hash}"', 'href="app.html${location.hash}"'),
    ('Switch to English', 'Tukar ke Bahasa Melayu'),
    ('>EN</a>', '>BM</a>'),
    ('<b>AI (EN):</b> "Members, we are now discussing the 8% dividend distribution from the RM 1.42 million surplus..."',
     '<b>AI (MS):</b> "Ahli sekalian, kita kini membincangkan pembahagian dividen 8% daripada lebihan RM 1.42 juta..."'),
    ('AI Auto-Translate (EN):</span> "I fully support the 8% dividend rate — it is reasonable and aligned with this year\'s performance."',
     'AI Auto-Translate (MS):</span> "Saya menyokong penuh kadar dividen 8% — ia munasabah dan selari dengan prestasi tahun ini."'),
]


def translate(text):
    for src, dst in sorted(PAIRS, key=lambda p: -len(p[0])):
        text = text.replace(src, dst)
    return text


def main():
    app = translate((ROOT / "app.js").read_text(encoding="utf-8"))
    for src, dst in EN_FIXUPS:
        app = app.replace(src, dst)
    (ROOT / "app-en.js").write_text(app, encoding="utf-8")

    data = translate((ROOT / "data.js").read_text(encoding="utf-8"))
    (ROOT / "data-en.js").write_text(data, encoding="utf-8")
    print("Wrote app-en.js and data-en.js")


if __name__ == "__main__":
    main()
